# Generated by Django 4.0.3 on 2022-07-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'subscribers', 'verbose_name_plural': 'sub'},
        ),
    ]
